// ── Demolition / Strip-Out Data ───────────────────────────────────────────────
// UK domestic 2024 defaults (ex-VAT). All costs are per-unit totals.

export type DemoUnit = 'item' | 'm²' | 'lm' | 'm³' | 'day' | 'skip' | 'provisional'

export const DEMO_UNIT_LABELS: Record<DemoUnit, string> = {
  item:        'Item',
  'm²':        'm²',
  lm:          'Lin m',
  'm³':        'm³',
  day:         'Day',
  skip:        'Skip',
  provisional: 'P/Sum',
}

export const DEMO_UNITS: DemoUnit[] = ['item', 'm²', 'lm', 'm³', 'day', 'skip', 'provisional']

export interface DemoTask {
  id:                  string
  name:                string
  clientDescription:   string   // client-facing quote text
  unit:                DemoUnit
  defaultQty:          number
  labourCost:          number   // cost per unit
  materialCost:        number
  plantCost:           number
  wasteCost:           number
  subcontractorCost:   number
  otherCost:           number
  showInTakeoff:       boolean
  showInAiScope:       boolean
  warnings?:           string[]
  aiKeywords?:         string[]
}

export interface DemoSubphase {
  id:        string
  name:      string
  markupPct: number
  tasks:     DemoTask[]
  warnings?: string[]
}

// ── Default demolition data ────────────────────────────────────────────────────

export const DEFAULT_DEMO_SUBPHASES: DemoSubphase[] = [
  {
    id: 'structural',
    name: 'Structural Demolition',
    markupPct: 25,
    warnings: [
      'Structural walls require engineer design and approval before works commence.',
      'Temporary propping and acrow supports may be required.',
      'Services (gas, electric, water) must be isolated before structural demolition.',
    ],
    tasks: [
      {
        id: 'structural-lbw',
        name: 'Remove load-bearing wall',
        clientDescription: 'Remove existing load-bearing masonry wall, including temporary propping, insert structural beam/lintel to engineer specification, make good to all faces. Allowance for structural engineer fee included.',
        unit: 'lm',
        defaultQty: 3,
        labourCost: 160,
        materialCost: 50,
        plantCost: 40,
        wasteCost: 80,
        subcontractorCost: 180,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: ['Structural engineer sign-off required.', 'Acrow props needed during works.', 'Check for hidden services in wall.'],
        aiKeywords: ['knock through', 'remove load bearing', 'remove load-bearing', 'structural wall', 'rsj', 'steel beam'],
      },
      {
        id: 'structural-masonry',
        name: 'Remove masonry wall',
        clientDescription: 'Break out and remove existing masonry wall (non-structural). Clear debris, make good to floor, ceiling and adjacent walls.',
        unit: 'lm',
        defaultQty: 3,
        labourCost: 90,
        materialCost: 10,
        plantCost: 20,
        wasteCost: 60,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove wall', 'knock down wall', 'demolish wall', 'break out wall'],
      },
      {
        id: 'structural-chimney',
        name: 'Break out chimney breast',
        clientDescription: 'Remove chimney breast and associated masonry back to structural shell. Include temporary support to chimney stack above, make good to floor, ceiling and walls. Structural engineer inspection included.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 450,
        materialCost: 80,
        plantCost: 60,
        wasteCost: 180,
        subcontractorCost: 200,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: ['Engineer sign-off required for chimney breast removal.', 'Stack above must be independently supported.'],
        aiKeywords: ['chimney breast', 'remove chimney', 'chimney removal'],
      },
      {
        id: 'structural-opening',
        name: 'Form structural opening',
        clientDescription: 'Form new structural opening in existing masonry wall, include temporary propping, supply and fix structural steel lintel/beam to engineer specification, padstones, reinstate masonry courses.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 280,
        materialCost: 600,
        plantCost: 50,
        wasteCost: 60,
        subcontractorCost: 200,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: ['Structural engineer design required.', 'Temporary propping essential before cutting.'],
        aiKeywords: ['new opening', 'form opening', 'structural opening', 'knock through wall'],
      },
      {
        id: 'structural-slab',
        name: 'Break out concrete slab',
        clientDescription: 'Break out existing reinforced / mass concrete floor slab using diamond saw and breaker. Remove arisings and dispose off site.',
        unit: 'm²',
        defaultQty: 10,
        labourCost: 28,
        materialCost: 0,
        plantCost: 18,
        wasteCost: 22,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['break out slab', 'remove concrete slab', 'break up floor', 'concrete break'],
      },
    ],
  },
  {
    id: 'non-structural',
    name: 'Non-Structural Demolition',
    markupPct: 20,
    tasks: [
      {
        id: 'ns-stud-wall',
        name: 'Remove stud wall',
        clientDescription: 'Remove existing timber stud partition wall, clear all framing, noggings and fixings. Make good to floor, ceiling and adjacent walls.',
        unit: 'm²',
        defaultQty: 12,
        labourCost: 22,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 12,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove stud wall', 'stud partition', 'remove partition', 'timber stud'],
      },
      {
        id: 'ns-partition',
        name: 'Remove partition wall',
        clientDescription: 'Remove existing non-structural blockwork / brick partition wall. Clear debris and make good at floor and ceiling.',
        unit: 'm²',
        defaultQty: 10,
        labourCost: 30,
        materialCost: 0,
        plantCost: 10,
        wasteCost: 18,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove partition', 'partition wall removal'],
      },
      {
        id: 'ns-cupboards',
        name: 'Remove built-in cupboards / boxing',
        clientDescription: 'Remove existing built-in cupboards, wardrobes or boxing-in. Carefully dismantle, remove arisings, make good wall and floor.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 90,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 25,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove cupboard', 'remove built-in', 'remove wardrobe', 'remove boxing'],
      },
      {
        id: 'ns-doors',
        name: 'Remove internal doors / frames',
        clientDescription: 'Remove existing internal door, frame, linings and architraves. Make good to wall opening.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 55,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 18,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove door', 'remove internal door', 'take off door'],
      },
    ],
  },
  {
    id: 'ceiling-strip',
    name: 'Ceiling Strip Out',
    markupPct: 18,
    warnings: [
      'Pre-1980s properties may contain asbestos in artex / textured coatings — survey recommended before stripping.',
    ],
    tasks: [
      {
        id: 'ceil-plasterboard',
        name: 'Strip plasterboard ceiling',
        clientDescription: 'Strip and remove existing plasterboard ceiling, including all fixings and noggins. Clear arisings and dispose off site.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 10,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 9,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['strip ceiling', 'remove plasterboard ceiling', 'plasterboard ceiling'],
      },
      {
        id: 'ceil-lath-plaster',
        name: 'Remove lath and plaster ceiling',
        clientDescription: 'Remove existing lath and plaster ceiling, including all timber laths, plaster and debris. Clear and dispose off site.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 16,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 14,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: ['Possible asbestos risk in older properties — recommend survey.'],
        aiKeywords: ['lath and plaster', 'lath plaster ceiling', 'old ceiling'],
      },
      {
        id: 'ceil-insulation',
        name: 'Remove ceiling insulation',
        clientDescription: 'Remove and bag existing ceiling / loft insulation, dispose off site in accordance with waste regulations.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 5,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 6,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove insulation', 'ceiling insulation removal'],
      },
      {
        id: 'ceil-coving',
        name: 'Remove old coving',
        clientDescription: 'Carefully remove existing plaster coving, clear debris, make good at wall and ceiling junction.',
        unit: 'lm',
        defaultQty: 20,
        labourCost: 8,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 4,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove coving', 'strip coving'],
      },
    ],
  },
  {
    id: 'wall-finishes',
    name: 'Wall Finishes Strip Out',
    markupPct: 18,
    warnings: [
      'Artex and textured coatings on walls / ceilings in properties built before 1985 may contain asbestos. Recommend a type-2 asbestos survey before hacking off or sanding.',
    ],
    tasks: [
      {
        id: 'wf-hack-off',
        name: 'Hack off plaster',
        clientDescription: 'Hack off existing plaster to expose base masonry. Clear arisings and dispose off site. Ready for re-plastering.',
        unit: 'm²',
        defaultQty: 25,
        labourCost: 11,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 11,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['hack off plaster', 'remove plaster', 'strip plaster'],
      },
      {
        id: 'wf-dry-lining',
        name: 'Remove plasterboard dry lining',
        clientDescription: 'Remove existing plasterboard dry lining (dot and dab / timber frame). Remove all fixings and battens. Dispose off site.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 8,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 7,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove dry lining', 'remove plasterboard', 'dry lining removal'],
      },
      {
        id: 'wf-wall-tiles',
        name: 'Remove tiles from walls',
        clientDescription: 'Remove existing ceramic / porcelain wall tiles including adhesive backing. Make good to substrate. Dispose of arisings.',
        unit: 'm²',
        defaultQty: 15,
        labourCost: 14,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 11,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove wall tiles', 'strip tiles', 'tile removal'],
      },
      {
        id: 'wf-render',
        name: 'Remove render internally / externally',
        clientDescription: 'Remove existing sand/cement or pebbledash render. Clear and dispose off site. Ready for re-rendering.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 16,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 13,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove render', 'strip render', 'pebbledash removal', 'hack off render'],
      },
    ],
  },
  {
    id: 'floor-strip',
    name: 'Floor Strip Out',
    markupPct: 18,
    tasks: [
      {
        id: 'fs-floor-tiles',
        name: 'Remove floor tiles',
        clientDescription: 'Remove existing ceramic / porcelain / quarry floor tiles and adhesive bed. Prepare substrate. Dispose off site.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 13,
        materialCost: 0,
        plantCost: 6,
        wasteCost: 13,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove floor tiles', 'lift floor tiles', 'floor tile removal'],
      },
      {
        id: 'fs-floorboards',
        name: 'Lift timber floorboards',
        clientDescription: 'Carefully lift and remove existing timber floorboards. Stack and store for reuse or dispose off site as instructed.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 10,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 8,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['lift floorboards', 'remove floorboards', 'timber floor removal'],
      },
      {
        id: 'fs-soft-floor',
        name: 'Remove laminate / carpet / vinyl',
        clientDescription: 'Strip and remove existing laminate, carpet, vinyl or LVT floor covering including gripper rods / adhesive. Dispose off site.',
        unit: 'm²',
        defaultQty: 25,
        labourCost: 6,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 5,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove carpet', 'remove laminate', 'remove vinyl', 'strip floor'],
      },
      {
        id: 'fs-screed',
        name: 'Break out screed',
        clientDescription: 'Break out and remove existing floor screed using floor scabbler or breaker. Clear arisings and dispose off site.',
        unit: 'm²',
        defaultQty: 15,
        labourCost: 25,
        materialCost: 0,
        plantCost: 12,
        wasteCost: 18,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['break out screed', 'remove screed', 'screed removal'],
      },
    ],
  },
  {
    id: 'kitchen-bathroom',
    name: 'Kitchen / Bathroom Strip Out',
    markupPct: 20,
    warnings: [
      'Gas and electric services must be isolated by a qualified engineer before strip out commences.',
      'Water services must be capped off by a qualified plumber.',
    ],
    tasks: [
      {
        id: 'kb-kitchen',
        name: 'Remove kitchen units',
        clientDescription: 'Strip out existing kitchen units, including wall and base units, worktops, upstand and splashback. Disconnect appliances. Dispose off site.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 350,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 120,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove kitchen', 'strip kitchen', 'kitchen strip out', 'remove kitchen units'],
      },
      {
        id: 'kb-worktops',
        name: 'Remove worktops',
        clientDescription: 'Remove and dispose of existing worktops (laminate, stone or timber).',
        unit: 'item',
        defaultQty: 1,
        labourCost: 80,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 35,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove worktop', 'worktop removal'],
      },
      {
        id: 'kb-bathroom',
        name: 'Remove bathroom suite',
        clientDescription: 'Strip out existing bathroom suite including bath, basin, WC, shower tray/enclosure and associated pipework. Cap off services.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 220,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 90,
        subcontractorCost: 120,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove bathroom', 'strip bathroom', 'bathroom strip out', 'remove suite'],
      },
      {
        id: 'kb-sanitaryware',
        name: 'Remove sanitaryware',
        clientDescription: 'Remove individual sanitaryware item (WC, basin, bidet or shower). Cap off supply and waste connections.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 90,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 40,
        subcontractorCost: 60,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove wc', 'remove basin', 'remove toilet', 'remove sanitaryware'],
      },
      {
        id: 'kb-services',
        name: 'Cap off services — allowance',
        clientDescription: 'Allowance for isolating and capping off existing services (gas, water, electric) in preparation for strip out. Subject to inspection.',
        unit: 'provisional',
        defaultQty: 1,
        labourCost: 0,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 350,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: ['Gas work must be carried out by a Gas Safe registered engineer.', 'Electrical isolation must be carried out by a Part P qualified electrician.'],
        aiKeywords: ['cap off services', 'isolate services', 'services allowance'],
      },
    ],
  },
  {
    id: 'external-demo',
    name: 'External Demolition',
    markupPct: 20,
    tasks: [
      {
        id: 'ext-patio',
        name: 'Remove patio / paving',
        clientDescription: 'Break up and remove existing patio, flags, paving slabs or block paving. Dispose off site.',
        unit: 'm²',
        defaultQty: 20,
        labourCost: 12,
        materialCost: 0,
        plantCost: 6,
        wasteCost: 22,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove patio', 'remove paving', 'break up patio', 'patio demolition'],
      },
      {
        id: 'ext-garden-wall',
        name: 'Remove garden wall',
        clientDescription: 'Demolish and remove existing brick or block garden wall. Clear footings, dispose of arisings off site.',
        unit: 'lm',
        defaultQty: 5,
        labourCost: 30,
        materialCost: 0,
        plantCost: 5,
        wasteCost: 32,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove garden wall', 'demolish wall', 'garden wall removal'],
      },
      {
        id: 'ext-outbuilding',
        name: 'Remove outbuilding / shed',
        clientDescription: 'Demolish and remove existing timber or masonry outbuilding / garage / shed. Clear foundations. Dispose of all arisings off site.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 600,
        materialCost: 0,
        plantCost: 200,
        wasteCost: 400,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove shed', 'remove outbuilding', 'demolish shed', 'outbuilding removal', 'garage demolition'],
      },
      {
        id: 'ext-fencing',
        name: 'Remove fencing',
        clientDescription: 'Remove existing fencing panels, posts and concrete spurs. Dispose off site.',
        unit: 'lm',
        defaultQty: 10,
        labourCost: 12,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 9,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['remove fence', 'remove fencing', 'fence removal'],
      },
      {
        id: 'ext-concrete',
        name: 'Break out external concrete',
        clientDescription: 'Break up and remove existing external concrete slab, path or hardstanding. Dispose of arisings off site.',
        unit: 'm²',
        defaultQty: 10,
        labourCost: 28,
        materialCost: 0,
        plantCost: 18,
        wasteCost: 26,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['break out concrete', 'remove concrete path', 'external concrete'],
      },
    ],
  },
  {
    id: 'waste',
    name: 'Waste & Clearance',
    markupPct: 15,
    warnings: [
      'Waste must be disposed of at a licensed waste transfer station.',
      'Duty of Care — a waste transfer note must be retained for all waste disposed off site.',
      'Segregate waste where possible: timber, plasterboard, masonry and metal should be separated.',
    ],
    tasks: [
      {
        id: 'waste-skip',
        name: 'Skip allowance',
        clientDescription: 'Provision of skip hire for disposal of demolition arisings (mixed construction waste).',
        unit: 'skip',
        defaultQty: 2,
        labourCost: 0,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 0,
        otherCost: 310,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['skip', 'skip hire', 'waste disposal', 'clear waste'],
      },
      {
        id: 'waste-loading',
        name: 'Labour loading out',
        clientDescription: 'Labour for loading demolition arisings into skip / lorry for disposal.',
        unit: 'day',
        defaultQty: 2,
        labourCost: 300,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['loading out', 'clear site', 'clean up', 'labour clearance'],
      },
      {
        id: 'waste-segregation',
        name: 'Waste segregation',
        clientDescription: 'Segregation of demolition waste into appropriate streams (plasterboard, timber, masonry, metals) to reduce landfill costs.',
        unit: 'day',
        defaultQty: 1,
        labourCost: 120,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['waste segregation', 'separate waste'],
      },
      {
        id: 'waste-hazardous',
        name: 'Hazardous material allowance',
        clientDescription: 'Provisional allowance for specialist disposal of hazardous materials found on site (asbestos, lead, contaminated waste). Subject to survey findings.',
        unit: 'provisional',
        defaultQty: 1,
        labourCost: 0,
        materialCost: 0,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 0,
        otherCost: 800,
        showInTakeoff: true,
        showInAiScope: true,
        warnings: [
          'Asbestos found in property built before 2000 — licensed removal contractor required.',
          'All hazardous waste must be removed by a licensed specialist contractor.',
          'Asbestos survey recommended before demolition in any pre-2000 property.',
        ],
        aiKeywords: ['asbestos', 'hazardous waste', 'asbestos removal', 'hazardous material'],
      },
      {
        id: 'waste-clean',
        name: 'Final sweep / clean down',
        clientDescription: 'Final sweep and clean down of all areas following completion of demolition and strip-out works. Dust protection removed.',
        unit: 'item',
        defaultQty: 1,
        labourCost: 280,
        materialCost: 40,
        plantCost: 0,
        wasteCost: 0,
        subcontractorCost: 0,
        otherCost: 0,
        showInTakeoff: true,
        showInAiScope: true,
        aiKeywords: ['clean down', 'final clean', 'sweep', 'post demolition clean'],
      },
    ],
  },
]

// ── LocalStorage helpers ──────────────────────────────────────────────────────

const LS_DEMO_KEY = 'sbc_custom_demo_subphases'

export function loadCustomDemoSubphases(): DemoSubphase[] {
  try {
    const raw = localStorage.getItem(LS_DEMO_KEY)
    return raw ? JSON.parse(raw) : []
  } catch { return [] }
}

export function saveCustomDemoSubphases(s: DemoSubphase[]): void {
  try { localStorage.setItem(LS_DEMO_KEY, JSON.stringify(s)) } catch {}
}

export function getAllDemoSubphases(custom: DemoSubphase[] = []): DemoSubphase[] {
  return [...DEFAULT_DEMO_SUBPHASES, ...custom]
}

// ── AI keyword matching ───────────────────────────────────────────────────────

export interface DemoMatch {
  subphase: DemoSubphase
  task: DemoTask
  score: number
}

export function matchDemoFromScope(scopeText: string): DemoMatch[] {
  const lower = scopeText.toLowerCase()
  const results: DemoMatch[] = []

  for (const sub of DEFAULT_DEMO_SUBPHASES) {
    for (const task of sub.tasks) {
      let score = 0
      for (const kw of task.aiKeywords ?? []) {
        if (lower.includes(kw.toLowerCase())) score += 2
      }
      if (score > 0) results.push({ subphase: sub, task, score })
    }
  }

  return results.sort((a, b) => b.score - a.score)
}

// ── Calculate selling price ───────────────────────────────────────────────────

export function calcDemoSellingPrice(
  labourCost: number,
  materialCost: number,
  plantCost: number,
  wasteCost: number,
  subcontractorCost: number,
  otherCost: number,
  markupPct: number,
): number {
  const base = labourCost + materialCost + plantCost + wasteCost + subcontractorCost + otherCost
  return +(base * (1 + markupPct / 100)).toFixed(2)
}
