import type { EstimatorItem, EstimatorItemTemplate } from './estimator'
import type { LabourTrade, TaskLabourLine } from './tradeRates'
export type { EstimatorItem, EstimatorItemTemplate, LabourTrade, TaskLabourLine }

export interface QuoteItem {
  id: number
  desc: string
  qty: number
  unit: string
  labour: number
  materials: number
  plantHire?: number
  subcontractors?: number
  other?: number
  itemType?: 'labour' | 'materials' | 'plant' | 'subcontractors' | 'other'
  notes: string
  /** Groups rows within a sub-phase into a named task (e.g. a layer name or task description) */
  taskGroup?: string
  /** Back Office task ID — set when the row originated from a bo_tasks row */
  boTaskId?: string
  /** Whether this row is included in totals — default true when not set */
  enabled?: boolean
}

/** A plant/equipment hire line item within a quote sub-phase, sourced from Back Office plant */
export interface QuotePlantItem {
  id:           string
  boPlantId?:   string     // bo_plant_items.id
  name:         string
  unit:         string
  qty:          number
  costPrice:    number
  sellPrice:    number
  notes?:       string
  enabled?:     boolean
}

/** A product/material line item within a quote sub-phase, sourced from Back Office products */
export interface QuoteProduct {
  id:           string     // local uid
  boProductId?: string     // bo_products.id — set when added from BO picker
  name:         string
  unit:         string
  qty:          number
  costPrice:    number     // cost per unit (from BO or overridden)
  sellPrice:    number     // sell price per unit (BO markup applied, or overridden)
  supplier?:    string
  category?:    string
  notes?:       string
  enabled?:     boolean    // toggle in/out of totals (default true)
  wastePercent?:number     // extra waste allowance
}

/** Metadata stamped on phases that were imported from the Takeoff tool */
export interface TakeoffPhaseMeta {
  importedFrom:  'takeoff'
  phaseName:     string          // original takeoff phase e.g. "External Walls"
  buildupType?:  string          // build-up name e.g. "Cavity Wall – Partial Fill"
  taskType?:     string          // task sub-phase name e.g. "Demolition"
  roomName?:     string          // location label e.g. "Rear Garden"
  drawingLabel?: string          // drawing element label e.g. "South Wall"
  measurements?: {
    length?:  number   // m
    area?:    number   // m²
    volume?:  number   // m³
    qty?:     number
    unit?:    string
    height?:  number   // m
    width?:   number   // m (foundation/trench)
    depth?:   number   // m (foundation/trench)
  }
}

export interface QuotePhase {
  id: number
  phase: string          // Sub-phase / category name
  parentPhase?: string   // Main phase grouping header
  /** Area / Room / Drawing-label grouping between Phase and Sub-phase */
  roomLabel?: string
  /** Free-text task name / description shown in the quote builder to explain what this sub-phase covers */
  taskName?: string
  items: QuoteItem[]
  estimatorItems?: EstimatorItem[]
  useEstimator?: boolean  // true = lump sums auto-computed from estimatorItems
  labourTrades?: LabourTrade[]  // explicit day-rate trade entries for this phase
  meta?: TakeoffPhaseMeta       // set when imported from the Takeoff tool
  /** Where this sub-phase originated */
  source?: 'takeoff' | 'ai' | 'manual'
  /**
   * Provenance/edit status — drives the status badge in the workspace.
   * bo-default  = unmodified copy of a Back Office default
   * edited      = started as bo-default but has been changed in this quote
   * manual      = added manually in this quote (no BO equivalent)
   * takeoff     = imported from the Takeoff tool
   * ai          = generated by AI scope writer
   */
  itemStatus?: 'bo-default' | 'edited' | 'manual' | 'takeoff' | 'ai'
  /** Back Office sub-phase ID — set when the phase originated from a bo_sub_phases row */
  boSubPhaseId?: string
  /** AI-generated item that couldn't be matched to Back Office master data */
  needsReview?: boolean
  reviewNote?: string
  /** Products/materials from Back Office product database */
  products?: QuoteProduct[]
  /** Plant & equipment hire items from Back Office plant database */
  plantItems?: QuotePlantItem[]
  /** Set true when the AI phase-review has been run and "Complete Phase" clicked */
  aiReviewed?: boolean
  /** Visual assigned during AI phase review — shown in workspace + client quote */
  phaseImage?: { emoji: string; color: string; photoUrl?: string }
}

export interface QuoteCustomer {
  name: string
  address: string
  email: string
  phone: string
}

export interface Quote {
  id: string
  ref: string
  savedDate: string
  lastEdited: string
  status:
    | 'draft'        // saved but incomplete — not yet ready to send
    | 'pending'      // ready, not yet sent (legacy)
    | 'in-progress'  // actively being worked on
    | 'review'       // ready for internal review
    | 'sent'         // sent to client
    | 'approved'     // client approved
    | 'rejected'     // client rejected
    | 'archived'     // closed / filed
    | 'accepted'     // legacy alias for approved
    | 'declined'     // legacy alias for rejected
  /** How the quote was created */
  quoteSource?: 'takeoff' | 'ai' | 'manual' | 'quick'
  jobType: string
  markup: number
  vatIncluded: boolean
  scope: string
  photo: string
  convertedToJob: boolean
  customer: QuoteCustomer
  phases: QuotePhase[]
  clientApprovedAt?: string | null
  clientApprovedBy?: string | null
}

export interface Job {
  id: string
  client: string
  type: string
  address: string
  value: number
  stage: 'planning' | 'active' | 'onhold' | 'complete'
  start: string
  weeks: number
  done: number
  notes: string
  quoteId?: string
}

// ── Job documents & cost ledger (doc-scan feature) ────────────────────────────

export type JobCostCategory = 'labour' | 'materials' | 'plant' | 'subcontractors' | 'other'
export type PaymentStatus = 'unknown' | 'unpaid' | 'partial' | 'paid'

export interface JobDocument {
  id: string
  jobId?: string
  quoteId?: string
  fileName: string
  storagePath: string
  mimeType: string
  fileSize: number
  status: 'uploaded' | 'extracted' | 'reviewed' | 'error'
  createdAt?: string
}

export interface JobCost {
  id: string
  jobId?: string
  quoteId?: string
  documentId?: string
  supplier: string
  docDate: string        // YYYY-MM-DD or ''
  docNumber: string
  description: string
  costCategory: JobCostCategory
  netAmount: number
  vatAmount: number
  grossAmount: number
  paymentStatus: PaymentStatus
  source: 'document' | 'manual'
  createdAt?: string
}

export interface InboxDocument {
  id: string
  jobId?: string
  fileName: string
  storagePath: string
  mimeType: string
  fileSize: number
  status: 'unallocated' | 'allocated' | 'error'
  extraction?: Record<string, unknown> | null   // raw_extraction snapshot
  createdAt?: string
}

export interface Supplier {
  id: string
  name: string
  contactName: string
  phone: string
  email: string
  address: string
  notes: string
  accountNumber: string
  addedFrom: string
  xeroContactId?: string | null   // reserved for Xero sync
}

export type PortalStatus = 'no_email' | 'not_invited' | 'invited' | 'active'

/**
 * Per-client settings controlling what the client sees in their portal,
 * in emailed PDFs, and in HTML quote views.
 */
export interface ClientPortalSettings {
  /** How much quote detail the client sees in the portal and HTML client view */
  quoteView: 'full' | 'phases' | 'total_only'
  /** Show the Scope of Works section in PDFs and HTML quotes */
  showScope: boolean
  /** Show the Payment Terms & Conditions section in PDFs and HTML quotes */
  showPaymentTerms: boolean
  /** Show the Quotes tab in the client portal */
  showQuotesTab: boolean
  /** Show the Jobs tab in the client portal */
  showJobsTab: boolean
  /** Show the Invoices tab in the client portal */
  showInvoicesTab: boolean
  /** Show the Programme (Gantt chart) on the Jobs page */
  showProgramme: boolean
  /** Allow client to digitally approve quotes via the portal */
  allowOnlineApproval: boolean
  /** Pre-selects the PDF type when sending a quote — 'customer' hides prices */
  defaultPdfType: 'customer' | 'detailed'
}

export const DEFAULT_CLIENT_PORTAL_SETTINGS: ClientPortalSettings = {
  quoteView:          'full',
  showScope:          true,
  showPaymentTerms:   false,
  showQuotesTab:      true,
  showJobsTab:        true,
  showInvoicesTab:    true,
  showProgramme:      true,
  allowOnlineApproval: true,
  defaultPdfType:     'customer',
}

export interface Client {
  id: string
  name: string
  first: string
  last: string
  phone: string
  email: string
  address: string
  notes: string
  addedFrom: string
  portalInvitedAt?: string | null
  portalStatus?: PortalStatus
  portalLastLogin?: string | null
  portalSettings?: ClientPortalSettings
}

export interface Settings {
  name: string
  tagline: string
  contact: string
  phone: string
  email: string
  address: string
  terms: string
  extra: string
  logo: string
  // Invoice defaults
  invoiceVatDefault?: boolean        // pre-tick VAT on new invoices (default true)
  invoicePaymentDays?: number        // days until due date on new invoices (default 30)
  invoicePaymentMethods?: string[]   // e.g. ['Bank Transfer', 'BACS']
  invoiceBankName?: string
  invoiceAccountName?: string
  invoiceSortCode?: string
  invoiceAccountNumber?: string
  invoiceDefaultNotes?: string       // pre-fills the invoice notes field
}

export interface GanttPhase {
  label: string
  startDay: number
  durDays: number
  id?: string
  level?: 0 | 1 | 2   // 0 = parentPhase group header, 1 = phase bar, 2 = task bar
  parentId?: string
  collapsed?: boolean
}

export interface GanttState {
  phases: GanttPhase[]
  totalDays: number
}

export interface InvoiceLineItem {
  id: number
  desc: string
  qty: number
  unitPrice: number
  total: number
}

export interface PaymentMilestone {
  id: number
  description: string
  amount: number
  dueDate: string
  paid: boolean
  paidDate: string
}

export interface Invoice {
  id: string
  ref: string
  jobId: string
  quoteId: string
  clientName: string
  clientAddress: string
  clientEmail: string
  lineItems: InvoiceLineItem[]
  subtotal: number
  vatIncluded: boolean
  vatAmount: number
  total: number
  status: 'draft' | 'sent' | 'paid' | 'overdue'
  issueDate: string
  dueDate: string
  notes: string
  createdAt: string
  paymentPlan: PaymentMilestone[] | null
  /** When true the invoice is pushed to Xero Accounting on save */
  syncToXero?: boolean
  /** Xero InvoiceID once the invoice has been successfully pushed */
  xeroInvoiceId?: string
}

export interface JobNote {
  id: string
  jobId: string
  note: string
  createdAt: string
}

export interface TemplatePhaseData {
  parentPhase: string
  phase: string
  items: Omit<QuoteItem, 'id'>[]
  estimatorItems?: EstimatorItemTemplate[]
}

// ── Team Members & Permissions ────────────────────────────────

export interface UserPermissions {
  dashboard:   boolean
  calendar:    boolean
  jobs:        boolean
  quotes:      boolean
  invoices:    boolean
  clients:     boolean
  settings:    boolean
  back_office: boolean
  team:        boolean
}

export type TeamMemberRole   = 'admin' | 'manager' | 'staff' | 'view_only'
export type TeamMemberStatus = 'invited' | 'active' | 'disabled'

export interface TeamMember {
  id:           string
  ownerId:      string
  authUserId:   string | null
  email:        string
  name:         string
  role:         TeamMemberRole
  status:       TeamMemberStatus
  permissions:  UserPermissions
  inviteToken:  string | null
  invitedAt:    string | null
  lastActiveAt: string | null
  createdAt:    string
}

export const FULL_PERMISSIONS: UserPermissions = {
  dashboard: true, calendar: true, jobs: true, quotes: true,
  invoices: true, clients: true, settings: true, back_office: true, team: true,
}

export const ROLE_PERMISSIONS: Record<TeamMemberRole, UserPermissions> = {
  admin: {
    dashboard: true, calendar: true, jobs: true, quotes: true,
    invoices: true, clients: true, settings: true, back_office: true, team: true,
  },
  manager: {
    dashboard: true, calendar: true, jobs: true, quotes: true,
    invoices: true, clients: true, settings: false, back_office: false, team: false,
  },
  staff: {
    dashboard: true, calendar: true, jobs: true, quotes: false,
    invoices: false, clients: false, settings: false, back_office: false, team: false,
  },
  view_only: {
    dashboard: true, calendar: true, jobs: false, quotes: false,
    invoices: false, clients: false, settings: false, back_office: false, team: false,
  },
}

// ── Variations / Change Orders ───────────────────────────────

export type VariationStatus =
  | 'draft'
  | 'sent'
  | 'approved'
  | 'rejected'
  | 'cancelled'
  | 'invoiced'
  | 'paid'

export interface VariationLineItem {
  id: number
  itemType: 'labour' | 'materials' | 'plant' | 'subcontractors' | 'other'
  desc: string
  qty: number
  unit: string
  rate: number   // cost rate per unit; selling price = rate × (1 + markup/100)
  notes: string
}

export interface Variation {
  id: string
  jobId: string
  ref: string
  title: string
  description: string
  status: VariationStatus
  items: VariationLineItem[]
  markup: number
  vatIncluded: boolean
  total: number           // final total (sell + VAT if applicable)
  notes: string
  locked: boolean
  clientApprovedAt: string | null
  clientApprovedBy: string | null
  clientRejectedAt: string | null
  clientRejectionReason: string | null
  sentAt: string | null
  createdAt: string
}
